runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "1m"

handlers:

- url: /static
  static_dir: static/

#new handlers should go ABOVE the catch all url (.*)
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
